CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  full_name TEXT,
  phone TEXT,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  verification_token TEXT,
  verification_token_expires TIMESTAMPTZ,
  reset_token TEXT,
  reset_token_expires TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ai_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_type TEXT NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 0,
  last_request TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, service_type)
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(12, 2) NOT NULL,
  image TEXT,
  badge TEXT,
  in_stock BOOLEAN NOT NULL DEFAULT TRUE,
  extended_description TEXT,
  nutrition JSONB NOT NULL DEFAULT '[]'::jsonb,
  origin TEXT,
  reviews JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  total_price NUMERIC(12, 2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  cancellation_reason TEXT,
  delivery_address TEXT,
  delivery_schedule TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS crm_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'operador',
  local_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS crm_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT,
  type TEXT,
  severity TEXT,
  message TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  owner_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL DEFAULT 'popup',
  interested_product TEXT,
  discount_code TEXT,
  subscribed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  user_id BIGINT,
  session_id TEXT,
  device_type TEXT,
  os_name TEXT,
  meta_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  plan_code TEXT,
  egg_type TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  next_delivery_date DATE,
  notes TEXT,
  monthly_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_newsletter_email ON newsletter_subscribers(email);
CREATE INDEX IF NOT EXISTS idx_analytics_event_name ON analytics_events(event_name);

INSERT INTO products (name, description, price, image, badge, in_stock, extended_description, nutrition, origin, reviews)
VALUES
  (
    'Huevo Blanco Extra',
    'Nuestro producto insignia para cocina diaria, con trazabilidad de origen y frescura de granja.',
    7800,
    '/images/HUEVOS_EXTRA.webp',
    'Más Vendido',
    TRUE,
    'Huevos de campo seleccionados para uso diario en cocina familiar y preparaciones de volumen. Balance ideal entre sabor, textura y rendimiento.',
    '["Proteína: 6g por unidad", "Grasas saludables: 5g por unidad", "Vitamina B12 y colina"]'::jsonb,
    'Granja Los Aromos, Región del Maule',
    '["Muy parejos de tamaño y de excelente sabor.", "Ideal para desayunos y repostería en casa.", "Se nota fresco, llega siempre en buen estado."]'::jsonb
  ),
  (
    'Gallina Libre (Happy Eggs)',
    'Huevos de gallinas criadas en libertad bajo pastoreo rotativo. Perfil premium para recetas de autor.',
    12500,
    '/images/HUEVOS_GALLINA_FELIZ.webp',
    'Premium',
    TRUE,
    'Huevos de gallinas libres con alimentación natural y crianza responsable. Sabor más intenso y yema de color más profundo para recetas premium.',
    '["Proteína: 6.5g por unidad", "Perfil lipídico equilibrado", "Aporte natural de vitaminas A y D"]'::jsonb,
    'Granja Los Aromos, Región del Maule',
    '["La yema tiene un color y sabor increíbles.", "Perfectos para brunch y platos más gourmet.", "Se siente la diferencia con huevos estándar."]'::jsonb
  ),
  (
    'Queso Mantecoso de Fundo',
    'Queso artesanal de campo, textura cremosa y fundido perfecto. Elaborado con leche fresca del día.',
    14500,
    '/images/queso_mantecoso.png',
    'Artesanal',
    TRUE,
    'Producido en el Fundo de Púa, Araucanía. Un queso de autor con maduración natural, sin aditivos, ideal para resaltar el sabor del sur en tu mesa.',
    '["Proteína: 25g por 100g", "Calcio natural", "Leche entera de vaca"]'::jsonb,
    'Fundo de Púa, Región de la Araucanía',
    '["El mejor queso mantecoso que he probado.", "Se nota la calidad de la leche, funde increíble.", "Un sabor auténtico a campo."]'::jsonb
  ),
  (
    'Queso Chanco Artesanal',
    'Receta clásica de fundo, con ojos irregulares y sabor madurado suave. Un clásico del sur.',
    13800,
    '/images/queso_chanco.png',
    'Tradicional',
    TRUE,
    'Elaborado bajo métodos tradicionales en el Fundo de Púa. Su textura semi-firme y aroma suave lo hacen el compañero ideal para aperitivos premium.',
    '["Proteína: 23g por 100g", "Bajo en sodio", "Rico en fósforo"]'::jsonb,
    'Fundo de Púa, Región de la Araucanía',
    '["Textura perfecta para la tabla de quesos.", "Muy suave y sabroso.", "Calidad superior a cualquier supermercado."]'::jsonb
  ),
  (
    'Longaniza Capitán Pastene',
    'Receta centenaria de colonos italianos. Carne seleccionada, ahumada en maderas nativas.',
    18900,
    '/images/longaniza_pastene.png',
    'Herencia Italiana',
    TRUE,
    'Producto icónico de Lumaco. Elaborada con 100% pulpa de cerdo, especias importadas y un ahumado lento que respeta las raíces de los colonos de Emilia-Romaña.',
    '["100% Carne de cerdo", "Sin gluten", "Ahumado natural"]'::jsonb,
    'Capitán Pastene, Región de la Araucanía',
    '["Sabor único, no se compara con nada.", "El ahumado es perfecto.", "Se nota la herencia italiana en el aliño."]'::jsonb
  ),
  (
    'Longaniza de Contulmo',
    'La receta clásica artesanal. Ahumado intenso y molienda rústica con especias locales.',
    16500,
    '/images/longaniza_contulmo.png',
    'Clásico Chileno',
    TRUE,
    'Desde las tierras de Contulmo, una longaniza que equilibra la tradición alemana y criolla. Jugosa, con el punto justo de especias y un ahumado característico.',
    '["Carne seleccionada", "Bajo contenido graso", "Condimentos naturales"]'::jsonb,
    'Contulmo, Región del Biobío',
    '["La longaniza definitiva para el asado.", "Muy jugosa y sabrosa.", "Excelente relación calidad-precio."]'::jsonb
  )
ON CONFLICT DO NOTHING;
